require "date"
require "open-uri"

puts "========== 🪓 Suppression des Tasks 🪓 ============="

Task.destroy_all

puts "========== 🔨 Suppression des Cultures 🔨 =========="

Culture.destroy_all

puts "========== ⛏️ Suppression des Users ⛏️ ============="

User.destroy_all

puts "========== 🪄 Créations des Users 🪄 ==============="
user = User.create!(email: "master@gmail.com", password: "123456", username: "Master", address: "Toronto")
User.create!(email: "diane@gmail.com", password: "123456", username: "Marguerite", address: "11 rue mauvoisins, 44200, Nantes")
User.create!(email: "vivien@gmail.com", password: "123456", username: "Vivien", address: "8 place crousillat, 13300, Salon-de-Provence")
User.create!(email: "clement@gmail.com", password: "123456", username: "Clement", address: "34 rue du bel-air, 74000, Annecy")
User.create!(email: "anne-sophie@gmail.com", password: "123456", username: "Anne-sophie", address: "12 Kruvale Rd, Port Arthur TAS 7182, Australie")

puts "========== 🪄 #{User.count} users crées ! 🪄 ==================="

puts "========== 🔮 Créations des Cultures 🔮 ============"

master_ciboulette = Culture.create!(name: "ciboulette", plantation_date: "2024-11-29", in_ground: false, outdoor: false, status: "Graine", master: true, user: user)
master_ciboulette.photo.attach(io: URI.open("https://images.unsplash.com/photo-1719722628937-4e83eade87f6?q=80&w=2073&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"), filename: "ciboulette.jpg", content_type: "image/jpeg")

master_tomate = Culture.create!(name: "tomate", plantation_date: "2024-11-29", in_ground: false, outdoor: false, status: "Graine", master: true, user: user)
master_tomate.photo.attach(io: URI.open("https://images.unsplash.com/photo-1534940519139-f860fb3c6e38?q=80&w=2067&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"), filename: "tomate.jpg", content_type: "image/jpeg")

master_butternut = Culture.create!(name: "butternut", plantation_date: "2024-11-29", in_ground: false, outdoor: false, status: "Graine", master: true, user: user)
master_butternut.photo.attach(io: URI.open("https://images.unsplash.com/photo-1575679472639-3f3fc9b86bf6?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"), filename: "butternut.jpg", content_type: "image/jpeg")

master_epinard = Culture.create!(name: "epinard", plantation_date: "2024-11-29", in_ground: false, outdoor: false, status: "Graine", master: true, user: user)
master_epinard.photo.attach(io: URI.open("https://images.unsplash.com/photo-1634731201932-9bd92839bea2?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"), filename: "epinard.jpg", content_type: "image/jpeg")

master_radis = Culture.create!(name: "radis", plantation_date: "2024-11-29", in_ground: false, outdoor: false, status: "Graine", master: true, user: user)
master_radis.photo.attach(io: URI.open("https://images.unsplash.com/photo-1593026122758-19bebc625104?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"), filename: "radis.jpg", content_type: "image/jpeg")

master_fraise = Culture.create!(name: "fraise", plantation_date: "2024-11-29", in_ground: false, outdoor: false, status: "Graine", master: true, user: user)
master_fraise.photo.attach(io: URI.open("https://images.unsplash.com/photo-1495570689269-d883b1224443?q=80&w=1931&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"), filename: "fraise.jpg", content_type: "image/jpeg")

puts "========== 🔮 #{Culture.count} Cultures crée 🔮 ==================="
puts "====== 🪄 Créations des Tasks associé aux cultures 🪄 ============"
puts "============= 🌿 Task pour Master Ciboulette 🌿 ============"

Task.create!(name: "Semer", description: "Semer les graines en pleine terre en les espaçant de 20 cm et à 10 cm de profondeur ou dans un grand pot en terre cuite de 30cm de diamètre.", date: nil, done: false,  order: nil, category: "Planter", delay: 0, culture: master_ciboulette)
Task.create!(name: "Arroser ", description: "arroser généreusement pour que la terre permette l'enracinement", date: nil, done: false,  order: nil, category: "Arroser", delay: 0, culture: master_ciboulette)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide", date: nil, done: false,  order: nil, category: "Arroser", delay: 3, culture: master_ciboulette)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide", date: nil, done: false,  order: nil, category: "Arroser", delay: 6, culture: master_ciboulette)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide", date: nil, done: false,  order: nil, category: "Arroser", delay: 9, culture: master_ciboulette)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide", date: nil, done: false,  order: nil, category: "Arroser", delay: 12, culture: master_ciboulette)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide", date: nil, done: false,  order: nil, category: "Arroser", delay: 14, culture: master_ciboulette)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide", date: nil, done: false,  order: nil, category: "Arroser", delay: 20, culture: master_ciboulette)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes autour des tiges de ciboulette pour éviter la concurrence", date: nil, done: false,  order: nil, category: "Arroser", delay: 3, culture: master_ciboulette)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes autour des tiges de ciboulette pour éviter la concurrence", date: nil, done: false,  order: nil, category: "Protéger", delay: 20, culture: master_ciboulette)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide", date: nil, done: false,  order: nil, category: "Arroser", delay: 25, culture: master_ciboulette)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes autour des tiges de ciboulette pour éviter la concurrence", date: nil, done: false,  order: nil, category: "Protéger", delay: 25, culture: master_ciboulette)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes autour des tiges de ciboulette pour éviter la concurrence", date: nil, done: false,  order: nil, category: "Protéger", delay: 30, culture: master_ciboulette)
Task.create!(name: "Tailler", description: "couper les fleurs pour favoriser la croissance des tiges", date: nil, done: false,  order: nil, category: "Tailler", delay: 30, culture: master_ciboulette)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide", date: nil, done: false,  order: nil, category: "Arroser", delay: 30, culture: master_ciboulette)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes autour des tiges de ciboulette pour éviter la concurrence", date: nil, done: false,  order: nil, category: "Protéger", delay: 35, culture: master_ciboulette)
Task.create!(name: "Tailler", description: "couper les fleurs pour favoriser la croissance des tiges", date: nil, done: false,  order: nil, category: "Tailler", delay: 35, culture: master_ciboulette)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide", date: nil, done: false,  order: nil, category: "Arroser", delay: 35, culture: master_ciboulette)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes autour des tiges de ciboulette pour éviter la concurrence", date: nil, done: false,  order: nil, category: "Protéger", delay: 40, culture: master_ciboulette)
Task.create!(name: "Récolter", description: "couper les tiges à 15 cm de hauteur, seulement la moitié des tiges à la fois", date: nil, done: false,  order: nil, category: "Récolter", delay: 40, culture: master_ciboulette)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide", date: nil, done: false,  order: nil, category: "Arroser", delay: 40, culture: master_ciboulette)
Task.create!(name: "Tailler", description: "couper les fleurs pour favoriser la croissance des tiges", date: nil, done: false,  order: nil, category: "Tailler", delay: 45, culture: master_ciboulette)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide", date: nil, done: false,  order: nil, category: "Arroser", delay: 45, culture: master_ciboulette)
Task.create!(name: "Récolter", description: "couper les tiges à 15 cm de hauteur, seulement la moitié des tiges à la fois", date: nil, done: false,  order: nil, category: "Récolter", delay: 50, culture: master_ciboulette)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide", date: nil, done: false,  order: nil, category: "Arroser", delay: 50, culture: master_ciboulette)
Task.create!(name: "Récolter", description: "couper les tiges à 15 cm de hauteur, seulement la moitié des tiges à la fois", date: nil, done: false,  order: nil, category: "Récolter", delay: 60, culture: master_ciboulette)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide", date: nil, done: false,  order: nil, category: "Arroser", delay: 60, culture: master_ciboulette)

puts "============= 🌿 Task pour Master Ciboulette crées ! 🌿 ============"
puts "============= 🍅 Task pour Master Tomate 🍅 ============"

Task.create!(name: "Semer", description: "semer au chaud et à la lumière dans des petits pots ou godets avec un engrais spécial semis", date: nil, done: false, order: nil, category: "Planter", delay: 0, culture: master_tomate)
Task.create!(name: "Arroser", description: "arroser généreusement pour que la terre et l'engrais permettent l'enracinement", date: nil, done: false, order: nil, category: "Arroser", delay: 0, culture: master_tomate)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide", date: nil, done: false, order: nil, category: "Arroser", delay: 3, culture: master_tomate)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide", date: nil, done: false, order: nil, category: "Arroser", delay: 6, culture: master_tomate)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide", date: nil, done: false, order: nil, category: "Arroser", delay: 9, culture: master_tomate)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide", date: nil, done: false, order: nil, category: "Arroser", delay: 12, culture: master_tomate)
Task.create!(name: "Repiquer", description: "repiquer les plants dans des petits pots individuels quand les premières feuilles apparaissent", date: nil, done: false, order: nil, category: "Planter", delay: 14, culture: master_tomate)
Task.create!(name: "Arroser", description: "arroser généreusement pour que la terre et l'engrais permettent l'enracinement", date: nil, done: false, order: nil, category: "Arroser", delay: 14, culture: master_tomate)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide", date: nil, done: false, order: nil, category: "Arroser", delay: 20, culture: master_tomate)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide", date: nil, done: false, order: nil, category: "Arroser", delay: 24, culture: master_tomate)
Task.create!(name: "Planter", description: "planter les jeunes plants en pleine terre en les espaçant de 50 cm et à 10 cm de profondeur ou dans un grand pot en terre cuite de 30cm de diamètre", date: nil, done: false, order: nil, category: "Planter", delay: 25, culture: master_tomate)
Task.create!(name: "Arroser", description: "arroser généreusement pour que la terre et l'engrais permettent l'enracinement", date: nil, done: false, order: nil, category: "Arroser", delay: 25, culture: master_tomate)
Task.create!(name: "Tuteurer", description: "planter profondément un bâton de 120 cm à 5 cm du pied de tomate et l'attacher de manière lâche à celui-ci pour le soutenir dans sa croissance", date: nil, done: false, order: nil, category: "Encourager", delay: 25, culture: master_tomate)
Task.create!(name: "Pailler", description: "recouvrir le pied de tomate de paille sur un diamètre de 20cm pour maintenir l'humidité du sol", date: nil, done: false, order: nil, category: "Protéger", delay: 25, culture: master_tomate)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles", date: nil, done: false, order: nil, category: "Arroser", delay: 28, culture: master_tomate)
Task.create!(name: "Tailler", description: "enlever les petites feuilles à l'aisselle des tiges pour permettre la croissance de la tige principale", date: nil, done: false, order: nil, category: "Tailler", delay: 28, culture: master_tomate)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles", date: nil, done: false, order: nil, category: "Arroser", delay: 31, culture: master_tomate)
Task.create!(name: "Tailler", description: "enlever les petites feuilles à l'aisselle des tiges pour permettre la croissance de la tige principale", date: nil, done: false, order: nil, category: "Tailler", delay: 35, culture: master_tomate)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles", date: nil, done: false, order: nil, category: "Arroser", delay: 35, culture: master_tomate)
Task.create!(name: "Apporter", description: "mettre au pied de la plante de l'engrais liquide enrichi en phosphore pour encourager la fructification", date: nil, done: false, order: nil, category: "Encourager", delay: 40, culture: master_tomate)
Task.create!(name: "Tailler", description: "enlever les petites feuilles à l'aisselle des tiges pour permettre la croissance de la tige principale", date: nil, done: false, order: nil, category: "Tailler", delay: 40, culture: master_tomate)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles", date: nil, done: false, order: nil, category: "Arroser", delay: 40, culture: master_tomate)
Task.create!(name: "Apporter", description: "mettre au pied de la plante de l'engrais liquide enrichi en phosphore pour encourager la fructification", date: nil, done: false, order: nil, category: "Encourager", delay: 40, culture: master_tomate)
Task.create!(name: "Tailler", description: "enlever les petites feuilles à l'aisselle des tiges pour permettre la croissance de la tige principale", date: nil, done: false, order: nil, category: "Tailler", delay: 45, culture: master_tomate)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles", date: nil, done: false, order: nil, category: "Arroser", delay: 45, culture: master_tomate)
Task.create!(name: "Tailler", description: "enlever les petites feuilles à l'aisselle des tiges pour permettre la croissance de la tige principale", date: nil, done: false, order: nil, category: "Tailler", delay: 50, culture: master_tomate)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles", date: nil, done: false, order: nil, category: "Arroser", delay: 50, culture: master_tomate)
Task.create!(name: "Tailler", description: "enlever les petites feuilles à l'aisselle des tiges pour permettre la croissance de la tige principale", date: nil, done: false, order: nil, category: "Tailler", delay: 55, culture: master_tomate)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles", date: nil, done: false, order: nil, category: "Arroser", delay: 55, culture: master_tomate)
Task.create!(name: "Tailler", description: "enlever les petites feuilles à l'aisselle des tiges pour permettre la croissance de la tige principale", date: nil, done: false, order: nil, category: "Tailler", delay: 60, culture: master_tomate)
Task.create!(name: "Arroser ", description: "arroser pour maintenir la terre humide sans mouiller les feuilles", date: nil, done: false, order: nil, category: "Arroser", delay: 60, culture: master_tomate)
Task.create!(name: "Tailler", description: "enlever les petites feuilles à l'aisselle des tiges pour permettre la croissance de la tige principale", date: nil, done: false, order: nil, category: "Tailler", delay: 65, culture: master_tomate)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles", date: nil, done: false, order: nil, category: "Arroser", delay: 65, culture: master_tomate)
Task.create!(name: "Tailler", description: "enlever les petites feuilles à l'aisselle des tiges pour permettre la croissance de la tige principale", date: nil, done: false, order: nil, category: "Tailler", delay: 70, culture: master_tomate)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles", date: nil, done: false, order: nil, category: "Arroser", delay: 70, culture: master_tomate)
Task.create!(name: "Tailler", description: "enlever les petites feuilles à l'aisselle des tiges pour permettre la croissance de la tige principale", date: nil, done: false, order: nil, category: "Tailler", delay: 75, culture: master_tomate)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles", date: nil, done: false, order: nil, category: "Arroser", delay: 75, culture: master_tomate)
Task.create!(name: "Tailler", description: "enlever les petites feuilles à l'aisselle des tiges pour permettre la croissance de la tige principale", date: nil, done: false, order: nil, category: "Tailler", delay: 80, culture: master_tomate)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles", date: nil, done: false, order: nil, category: "Arroser", delay: 80, culture: master_tomate)
Task.create!(name: "Récolter", description: "récolter les tomates lorsqu'elles sont bien colorées et fermes au toucher", date: nil, done: false, order: nil, category: "Récolter", delay: 80, culture: master_tomate)
Task.create!(name: "Arroser", description: "arroser généreusement", date: nil, done: false, order: nil, category: "Arroser", delay: 90, culture: master_tomate)
Task.create!(name: "Récolter", description: "récolter les tomates lorsqu'elles sont bien colorées et fermes au toucher", date: nil, done: false, order: nil, category: "Récolter", delay: 90, culture: master_tomate)
Task.create!(name: "Tailler", description: "enlever les petites feuilles à l'aisselle des tiges pour permettre la croissance de la tige principale", date: nil, done: false, order: nil, category: "Tailler", delay: 100, culture: master_tomate)
Task.create!(name: "Arroser", description: "arroser généreusement", date: nil, done: false, order: nil, category: "Arroser", delay: 100, culture: master_tomate)
Task.create!(name: "Récolter", description: "récolter les tomates lorsqu'elles sont bien colorées et fermes au toucher", date: nil, done: false, order: nil, category: "Récolter", delay: 100, culture: master_tomate)
Task.create!(name: "Tailler", description: "enlever les petites feuilles à l'aisselle des tiges pour permettre la croissance de la tige principale", date: nil, done: false, order: nil, category: "Tailler", delay: 110, culture: master_tomate)
Task.create!(name: "Récolter", description: "récolter les tomates lorsqu'elles sont bien colorées et fermes au toucher", date: nil, done: false, order: nil, category: "Récolter", delay: 110, culture: master_tomate)
Task.create!(name: "Arracher", description: "arracher le plant qui doit être desséché et sans fruits mûrs", date: nil, done: false, order: nil, category: "Arracher", delay: 120, culture: master_tomate)

puts "============= 🍅 Task pour Master Tomate crées ! 🍅 ============"
puts "============= 🍠 Task pour Master Butternut 🍠 ============"

Task.create!(name: "Semer", description: "semer au chaud et à l'ombre dans des petits pots ou godets avec un engrais spécial semis", date: nil, done: false, order: nil, category: "Planter", delay: 0, culture: master_butternut)
Task.create!(name: "Arroser", description: "arroser généreusement pour que la terre permette la germination", date: nil, done: false, order: nil, category: "Arroser", delay: 0, culture: master_butternut)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide", date: nil, done: false, order: nil, category: "Arroser", delay: 3, culture: master_butternut)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide", date: nil, done: false, order: nil, category: "Arroser", delay: 6, culture: master_butternut)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide", date: nil, done: false, order: nil, category: "Arroser", delay: 9, culture: master_butternut)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide", date: nil, done: false, order: nil, category: "Arroser", delay: 12, culture: master_butternut)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide", date: nil, done: false, order: nil, category: "Arroser", delay: 14, culture: master_butternut)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide", date: nil, done: false, order: nil, category: "Arroser", delay: 20, culture: master_butternut)
Task.create!(name: "Repiquer", description: "planter les jeunes plants en pleine terre en les espaçant de 1,5 à 2m ou dans un grand pot en terre cuite de 50cm de diamètre avec un treillage", date: nil, done: false, order: nil, category: "Planter", delay: 25, culture: master_butternut)
Task.create!(name: "Arroser", description: "arroser généreusement pour que la terre permette le développement", date: nil, done: false, order: nil, category: "Arroser", delay: 25, culture: master_butternut)
Task.create!(name: "Pincer", description: "pincer les tiges au-dessus de la 3ème feuille pour favoriser la fructification", date: nil, done: false, order: nil, category: "Encourager", delay: 30, culture: master_butternut)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide", date: nil, done: false, order: nil, category: "Arroser", delay: 30, culture: master_butternut)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes autour du pied pour éviter la concurrence", date: nil, done: false, order: nil, category: "Protéger", delay: 30, culture: master_butternut)
Task.create!(name: "Pailler", description: "recouvrir le pied de paille sur un diamètre de 20cm pour maintenir l'humidité du sol", date: nil, done: false, order: nil, category: "Protéger", delay: 30, culture: master_butternut)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles", date: nil, done: false, order: nil, category: "Arroser", delay: 35, culture: master_butternut)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes autour du pied pour éviter la concurrence", date: nil, done: false, order: nil, category: "Protéger", delay: 35, culture: master_butternut)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles", date: nil, done: false, order: nil, category: "Arroser", delay: 40, culture: master_butternut)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes autour du pied pour éviter la concurrence", date: nil, done: false, order: nil, category: "Protéger", delay: 40, culture: master_butternut)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles", date: nil, done: false, order: nil, category: "Arroser", delay: 45, culture: master_butternut)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes autour du pied pour éviter la concurrence", date: nil, done: false, order: nil, category: "Protéger", delay: 45, culture: master_butternut)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles", date: nil, done: false, order: nil, category: "Arroser", delay: 50, culture: master_butternut)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes autour du pied pour éviter la concurrence", date: nil, done: false, order: nil, category: "Protéger", delay: 50, culture: master_butternut)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles", date: nil, done: false, order: nil, category: "Arroser", delay: 55, culture: master_butternut)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes autour du pied pour éviter la concurrence", date: nil, done: false, order: nil, category: "Protéger", delay: 55, culture: master_butternut)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles", date: nil, done: false, order: nil, category: "Arroser", delay: 60, culture: master_butternut)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes autour du pied pour éviter la concurrence", date: nil, done: false, order: nil, category: "Protéger", delay: 60, culture: master_butternut)
Task.create!(name: "Pailler", description: "recouvrir le pied de paille sur un diamètre de 20cm pour maintenir l'humidité du sol", date: nil, done: false, order: nil, category: "Protéger", delay: 60, culture: master_butternut)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles", date: nil, done: false, order: nil, category: "Arroser", delay: 65, culture: master_butternut)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes autour du pied pour éviter la concurrence", date: nil, done: false, order: nil, category: "Protéger", delay: 65, culture: master_butternut)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles", date: nil, done: false, order: nil, category: "Arroser", delay: 70, culture: master_butternut)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes autour du pied pour éviter la concurrence", date: nil, done: false, order: nil, category: "Protéger", delay: 70, culture: master_butternut)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles", date: nil, done: false, order: nil, category: "Arroser", delay: 75, culture: master_butternut)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes autour du pied pour éviter la concurrence", date: nil, done: false, order: nil, category: "Protéger", delay: 75, culture: master_butternut)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles", date: nil, done: false, order: nil, category: "Arroser", delay: 80, culture: master_butternut)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes autour du pied pour éviter la concurrence", date: nil, done: false, order: nil, category: "Protéger", delay: 80, culture: master_butternut)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles", date: nil, done: false, order: nil, category: "Arroser", delay: 85, culture: master_butternut)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes autour du pied pour éviter la concurrence", date: nil, done: false, order: nil, category: "Protéger", delay: 85, culture: master_butternut)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles", date: nil, done: false, order: nil, category: "Arroser", delay: 90, culture: master_butternut)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes autour du pied pour éviter la concurrence", date: nil, done: false, order: nil, category: "Protéger", delay: 90, culture: master_butternut)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles", date: nil, done: false, order: nil, category: "Arroser", delay: 95, culture: master_butternut)
Task.create!(name: "Pailler", description: "recouvrir le pied de paille sur un diamètre de 20cm pour maintenir l'humidité du sol", date: nil, done: false, order: nil, category: "Protéger", delay: 95, culture: master_butternut)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles", date: nil, done: false, order: nil, category: "Arroser", delay: 100, culture: master_butternut)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes autour du pied pour éviter la concurrence", date: nil, done: false, order: nil, category: "Protéger", delay: 100, culture: master_butternut)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles", date: nil, done: false, order: nil, category: "Arroser", delay: 105, culture: master_butternut)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes autour du pied pour éviter la concurrence", date: nil, done: false, order: nil, category: "Protéger", delay: 105, culture: master_butternut)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles", date: nil, done: false, order: nil, category: "Arroser", delay: 110, culture: master_butternut)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes autour du pied pour éviter la concurrence", date: nil, done: false, order: nil, category: "Protéger", delay: 110, culture: master_butternut)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles", date: nil, done: false, order: nil, category: "Arroser", delay: 115, culture: master_butternut)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes autour du pied pour éviter la concurrence", date: nil, done: false, order: nil, category: "Protéger", delay: 115, culture: master_butternut)
Task.create!(name: "Récolter", description: "récolter les butternuts lorsqu'elles sont uniformément beiges et que le pédoncule commence à sécher", date: nil, done: false, order: nil, category: "Récolter", delay: 120, culture: master_butternut)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles", date: nil, done: false, order: nil, category: "Arroser", delay: 120, culture: master_butternut)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes autour du pied pour éviter la concurrence", date: nil, done: false, order: nil, category: "Protéger", delay: 120, culture: master_butternut)
Task.create!(name: "Récolter", description: "récolter les butternuts lorsqu'elles sont uniformément beiges et que le pédoncule commence à sécher", date: nil, done: false, order: nil, category: "Récolter", delay: 125, culture: master_butternut)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles", date: nil, done: false, order: nil, category: "Arroser", delay: 125, culture: master_butternut)
Task.create!(name: "Récolter", description: "récolter les butternuts lorsqu'elles sont uniformément beiges et que le pédoncule commence à sécher", date: nil, done: false, order: nil, category: "Récolter", delay: 130, culture: master_butternut)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles", date: nil, done: false, order: nil, category: "Arroser", delay: 140, culture: master_butternut)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes autour du pied pour éviter la concurrence", date: nil, done: false, order: nil, category: "Protéger", delay: 150, culture: master_butternut)
Task.create!(name: "Récolter", description: "récolter les butternuts lorsqu'elles sont uniformément beiges et que le pédoncule commence à sécher", date: nil, done: false, order: nil, category: "Récolter", delay: 160, culture: master_butternut)
Task.create!(name: "Arracher", description: "arracher le plant qui doit être desséché et sans fruits mûrs", date: nil, done: false, order: nil, category: "Arracher", delay: 160, culture: master_butternut)

puts "============= 🍠 Task pour Master Butternut crées ! 🍠 ============"
puts "============= 🌿 Task pour Master Epinard ! 🌿 ============"

Task.create!(name: "Semer", description: "semer les graines à la volée en ligne de 15 cm d'écart, en pleine terre à un emplacement ensoleillé.", date: nil, done: false, order: nil, category: "Planter", delay: 0, culture: master_epinard)
Task.create!(name: "Arroser", description: "arroser généreusement pour permettre l'enracinement.", date: nil, done: false, order: nil, category: "Arroser", delay: 0, culture: master_epinard)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide.", date: nil, done: false, order: nil, category: "Arroser", delay: 3, culture: master_epinard)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide.", date: nil, done: false, order: nil, category: "Arroser", delay: 6, culture: master_epinard)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide.", date: nil, done: false, order: nil, category: "Arroser", delay: 9, culture: master_epinard)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes autour des premières feuilles pour éviter la concurrence.", date: nil, done: false, order: nil, category: "Arracher", delay: 14, culture: master_epinard)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 14, culture: master_epinard)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 17, culture: master_epinard)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes pour éviter la concurrence.", date: nil, done: false, order: nil, category: "Arracher", delay: 20, culture: master_epinard)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 20, culture: master_epinard)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 23, culture: master_epinard)
Task.create!(name: "Eclaircir", description: "enlever un plant sur deux pour permettre un rang bien régulier. garder les plants arrachés pour les repiquer au bout du rang.", date: nil, done: false, order: nil, category: "Encourager", delay: 25, culture: master_epinard)
Task.create!(name: "Repiquer", description: "planter les plants arrachés précédemment au bout du rang dont il est issu.", date: nil, done: false, order: nil, category: "Planter", delay: 26, culture: master_epinard)
Task.create!(name: "Apporter", description: "mettre au pied de la plante de l'engrais enrichi en azote.", date: nil, done: false, order: nil, category: "Encourager", delay: 26, culture: master_epinard)
Task.create!(name: "Arroser", description: "arroser généreusement pour que la terre et l'engrais permettent l'enracinement.", date: nil, done: false, order: nil, category: "Arroser", delay: 26, culture: master_epinard)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes pour éviter la concurrence.", date: nil, done: false, order: nil, category: "Arracher", delay: 30, culture: master_epinard)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 30, culture: master_epinard)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 34, culture: master_epinard)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 37, culture: master_epinard)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes pour éviter la concurrence.", date: nil, done: false, order: nil, category: "Arracher", delay: 40, culture: master_epinard)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 40, culture: master_epinard)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 44, culture: master_epinard)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 47, culture: master_epinard)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes pour éviter la concurrence.", date: nil, done: false, order: nil, category: "Arracher", delay: 50, culture: master_epinard)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 50, culture: master_epinard)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 54, culture: master_epinard)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 57, culture: master_epinard)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes pour éviter la concurrence.", date: nil, done: false, order: nil, category: "Arracher", delay: 60, culture: master_epinard)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 60, culture: master_epinard)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 64, culture: master_epinard)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes pour éviter la concurrence.", date: nil, done: false, order: nil, category: "Arracher", delay: 69, culture: master_epinard)
Task.create!(name: "Récolter", description: "récolter les feuilles lorsqu'elles sont uniformément vertes.", date: nil, done: false, order: nil, category: "Récolter", delay: 70, culture: master_epinard)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 70, culture: master_epinard)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 75, culture: master_epinard)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes pour éviter la concurrence.", date: nil, done: false, order: nil, category: "Arracher", delay: 80, culture: master_epinard)
Task.create!(name: "Récolter", description: "récolter les feuilles lorsqu'elles sont uniformément vertes.", date: nil, done: false, order: nil, category: "Récolter", delay: 80, culture: master_epinard)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 80, culture: master_epinard)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 85, culture: master_epinard)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes pour éviter la concurrence.", date: nil, done: false, order: nil, category: "Arracher", delay: 90, culture: master_epinard)
Task.create!(name: "Récolter", description: "récolter les feuilles lorsqu'elles sont uniformément vertes.", date: nil, done: false, order: nil, category: "Récolter", delay: 90, culture: master_epinard)

puts "============= 🌿 Task pour Master Epinard crées ! 🌿 ============"
puts "============= 🍒 Task pour Master Radis ! 🍒 ============"

Task.create!(name: "Semer", description: "semer les graines à la volée à 1cm de profondeur en ligne de 20cm d'écart à un emplacement ensoleillé.", date: nil, done: false, order: nil, category: "Planter", delay: 0, culture: master_radis)
Task.create!(name: "Arroser", description: "arroser généreusement pour permettre l'enracinement.", date: nil, done: false, order: nil, category: "Arroser", delay: 0, culture: master_radis)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide.", date: nil, done: false, order: nil, category: "Arroser", delay: 3, culture: master_radis)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide.", date: nil, done: false, order: nil, category: "Arroser", delay: 6, culture: master_radis)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide.", date: nil, done: false, order: nil, category: "Arroser", delay: 9, culture: master_radis)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes autour des premières feuilles pour éviter la concurrence.", date: nil, done: false, order: nil, category: "Arracher", delay: 12, culture: master_radis)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 12, culture: master_radis)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 16, culture: master_radis)
Task.create!(name: "Eclaircir", description: "enlever un plant sur deux pour permettre un rang bien régulier. garder les plants arrachés pour les repiquer au bout du rang.", date: nil, done: false, order: nil, category: "Encourager", delay: 20, culture: master_radis)
Task.create!(name: "Planter", description: "planter les plants arrachés précédemment au bout du rang dont il est issu.", date: nil, done: false, order: nil, category: "Planter", delay: 20, culture: master_radis)
Task.create!(name: "Apporter", description: "mettre au pied de la plante de l'engrais.", date: nil, done: false, order: nil, category: "Encourager", delay: 20, culture: master_radis)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 20, culture: master_radis)
Task.create!(name: "Arroser", description: "arroser généreusement pour que la terre et l'engrais permettent l'enracinement.", date: nil, done: false, order: nil, category: "Arroser", delay: 23, culture: master_radis)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 26, culture: master_radis)
Task.create!(name: "Désherberr", description: "arracher les mauvaises herbes pour éviter la concurrence.", date: nil, done: false, order: nil, category: "Arracher", delay: 30, culture: master_radis)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 30, culture: master_radis)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 34, culture: master_radis)
Task.create!(name: "Récolter", description: "récolter les radis dès que la partie blanche apparaît bien visiblement entre la terre et les petites feuilles.", date: nil, done: false, order: nil, category: "Récolter", delay: 37, culture: master_radis)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 37, culture: master_radis)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes pour éviter la concurrence.", date: nil, done: false, order: nil, category: "Arracher", delay: 40, culture: master_radis)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 40, culture: master_radis)
Task.create!(name: "Récolter", description: "récolter les radis dès que la partie blanche apparaît bien visiblement entre la terre et les petites feuilles.", date: nil, done: false, order: nil, category: "Récolter", delay: 45, culture: master_radis)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 45, culture: master_radis)
Task.create!(name: "Récolter", description: "récolter les radis dès que la partie blanche apparaît bien visiblement entre la terre et les petites feuilles.", date: nil, done: false, order: nil, category: "Récolter", delay: 50, culture: master_radis)

puts "============= 🍒 Task pour Master Radis crées ! 🍒 ============"
puts "============= 🍓 Task pour Master Fraise ! 🍓 ============"

Task.create!(name: "Semer", description: "semer les graines en pots individuels à 5 cm de profondeur sous abri à un emplacement ombragé.", date: nil, done: false, order: nil, category: "Planter", delay: 0, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser généreusement pour permettre l'enracinement.", date: nil, done: false, order: nil, category: "Arroser", delay: 0, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide.", date: nil, done: false, order: nil, category: "Arroser", delay: 3, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide.", date: nil, done: false, order: nil, category: "Arroser", delay: 6, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide.", date: nil, done: false, order: nil, category: "Arroser", delay: 9, culture: master_fraise)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes autour des premières feuilles pour éviter la concurrence.", date: nil, done: false, order: nil, category: "Arracher", delay: 13, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 16, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 19, culture: master_fraise)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes autour des premières feuilles pour éviter la concurrence.", date: nil, done: false, order: nil, category: "Arracher", delay: 22, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 22, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 26, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 30, culture: master_fraise)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes autour des premières feuilles pour éviter la concurrence.", date: nil, done: false, order: nil, category: "Arracher", delay: 33, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 33, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 37, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 41, culture: master_fraise)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes autour des premières feuilles pour éviter la concurrence.", date: nil, done: false, order: nil, category: "Arracher", delay: 45, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 45, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 50, culture: master_fraise)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes autour des premières feuilles pour éviter la concurrence.", date: nil, done: false, order: nil, category: "Arracher", delay: 54, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 54, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 58, culture: master_fraise)
Task.create!(name: "Repiquer", description: "planter les petits plants avec leurs premières vraies feuilles dans de petits pots individuels.", date: nil, done: false, order: nil, category: "Planter", delay: 61, culture: master_fraise)
Task.create!(name: "Apporter", description: "mettre de l'engrais liquide et du compost pour encourager la fructification.", date: nil, done: false, order: nil, category: "Encourager", delay: 61, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser généreusement pour que la terre et l'engrais permettent l'enracinement.", date: nil, done: false, order: nil, category: "Arroser", delay: 61, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser généreusement sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 65, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 70, culture: master_fraise)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes pour éviter la concurrence.", date: nil, done: false, order: nil, category: "Arracher", delay: 75, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 75, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 80, culture: master_fraise)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes pour éviter la concurrence.", date: nil, done: false, order: nil, category: "Arracher", delay: 85, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 85, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 90, culture: master_fraise)
Task.create!(name: "Planter", description: "planter les jeunes plants en pleine terre en les espaçant de 35 cm et à 5 cm de profondeur.", date: nil, done: false, order: nil, category: "Planter", delay: 95, culture: master_fraise)
Task.create!(name: "Apporter", description: "mettre au pied de la plante du compost pour enrichir la terre.", date: nil, done: false, order: nil, category: "Apporter", delay: 95, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser généreusement pour permettre l'enracinement.", date: nil, done: false, order: nil, category: "Arroser", delay: 95, culture: master_fraise)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes pour éviter la concurrence.", date: nil, done: false, order: nil, category: "Arracher", delay: 100, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 100, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 105, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 110, culture: master_fraise)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes pour éviter la concurrence.", date: nil, done: false, order: nil, category: "Arracher", delay: 115, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 115, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 120, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 125, culture: master_fraise)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes pour éviter la concurrence.", date: nil, done: false, order: nil, category: "Arracher", delay: 130, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 130, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 135, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 140, culture: master_fraise)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes pour éviter la concurrence.", date: nil, done: false, order: nil, category: "Arracher", delay: 145, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 145, culture: master_fraise)
Task.create!(name: "Couper", description: "couper les premières fleurs pour favoriser l'enracinement.", date: nil, done: false, order: nil, category: "Couper", delay: 150, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 150, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 155, culture: master_fraise)
Task.create!(name: "Couper", description: "couper les premières fleurs pour favoriser l'enracinement.", date: nil, done: false, order: nil, category: "Couper", delay: 160, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 160, culture: master_fraise)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes pour éviter la concurrence.", date: nil, done: false, order: nil, category: "Arracher", delay: 165, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 165, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 170, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 175, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 180, culture: master_fraise)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes pour éviter la concurrence.", date: nil, done: false, order: nil, category: "Arracher", delay: 185, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 185, culture: master_fraise)
Task.create!(name: "Récolter", description: "récolter délicatement les fraises lorsqu'elles sont uniformément rouges, en pinçant la tige.", date: nil, done: false, order: nil, category: "Récolter", delay: 190, culture: master_fraise)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes pour éviter la concurrence.", date: nil, done: false, order: nil, category: "Arracher", delay: 190, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 190, culture: master_fraise)
Task.create!(name: "Récolter", description: "récolter délicatement les fraises lorsqu'elles sont uniformément rouges, en pinçant la tige.", date: nil, done: false, order: nil, category: "Récolter", delay: 195, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 195, culture: master_fraise)
Task.create!(name: "Récolter", description: "récolter délicatement les fraises lorsqu'elles sont uniformément rouges, en pinçant la tige.", date: nil, done: false, order: nil, category: "Récolter", delay: 200, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 200, culture: master_fraise)
Task.create!(name: "Désherber", description: "arracher les mauvaises herbes pour éviter la concurrence.", date: nil, done: false, order: nil, category: "Arracher", delay: 205, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 205, culture: master_fraise)
Task.create!(name: "Récolter", description: "récolter délicatement les fraises lorsqu'elles sont uniformément rouges, en pinçant la tige.", date: nil, done: false, order: nil, category: "Récolter", delay: 210, culture: master_fraise)
Task.create!(name: "Arroser", description: "arroser pour maintenir la terre humide sans mouiller les feuilles.", date: nil, done: false, order: nil, category: "Arroser", delay: 210, culture: master_fraise)
Task.create!(name: "Récolter", description: "récolter délicatement les fraises lorsqu'elles sont uniformément rouges, en pinçant la tige.", date: nil, done: false, order: nil, category: "Récolter", delay: 215, culture: master_fraise)

puts "============= 🍓 Task pour Master Fraise crées ! 🍓 ============"


puts "========== 🪄 #{Task.count} Tasks crées 🪄 ===================="

puts "========== 🌹🌺🪻 Seeding terminé 🪻🌺🌹 ==========="
